timezone: Asia/Shanghai
lang: zh_CN

title: 爱萝莉导航 - 与大家共享萝莉
alias_en: ILOLIDH
alias_cn: 爱萝莉导航
description: 福利网站哪里找,就来x福利导航网,福利导航包含各种岛国视频下载资源,在线资源,种子资源,福利资讯社区,温馨提示:请将你懂得福利导航加入收藏,下次一键访问,迅速便捷!
keywords: 爱萝莉导航,x福利,福利导航,福利导航大全,福利导航网,大香蕉视频,大香蕉导航,500导航,第一福利导航,福利网站大全
url: http://www.ilolidh.com

author: 13&14.
author_url: /
organization: ILOLIDH.COM
organization_url: /
contact: 411736232[at]qq[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg
logo_1: /images/logo-1.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor